name: Deploy Top Movies

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t top-movies .

      - name: Stop old container
        run: |
          docker stop top-movies-cont || true
          docker rm top-movies-cont || true

      - name: Run new container
        run: |
          docker run -d \
            --name top-movies-cont \
            -p 80:80 \
            top-movies
