name: Deploy Apache Site

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t top-movies .

      - name: Stop old container (if exists)
        run: docker rm -f top-movies || true

      - name: Run Apache container
        run: docker run -d -p 80:80 --name top-movies top-movies
